[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  timeout = 26

[[redirects]]
  from = "/api/admin-limpar-rotas"
  to = "/.netlify/functions/admin-limpar-rotas"
  status = 200

[[redirects]]
  from = "/api/omie"
  to = "/.netlify/functions/omie"
  status = 200

[[redirects]]
  from = "/api/omie-seguro"
  to = "/.netlify/functions/omie-seguro"
  status = 200

[[redirects]]
  from = "/api/firebase-read"
  to = "/.netlify/functions/firebase-read"
  status = 200

[[redirects]]
  from = "/api/firebase-write"
  to = "/.netlify/functions/firebase-write"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
